name: Build npm package

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    env:
      WORKING_DIRECTORY: Example
    concurrency:
      group: ios-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Build package
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: >-
          ./createNPMPackage.sh
      - name: Clone repository reanimated-rn-version-tester
        uses: actions/checkout@master
        with:
          name: piaskowyk/reanimated-rn-version-tester
          path: ${{ env.WORKING_DIRECTORY }}
      - name: Replace reanimated package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cp ../react-native-reanimated-*.tgz . && ./replace.sh

      